# Generated by Django 4.2 on 2023-04-30 19:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'DropType',
                'verbose_name_plural': 'DropTypes',
            },
        ),
        migrations.RemoveField(
            model_name='artist',
            name='slug_id',
        ),
        migrations.AddField(
            model_name='artist',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Avatar'),
        ),
        migrations.AddField(
            model_name='artist',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('88913227-36bf-4fe9-a1e9-c50ea0e58456'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Single',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('7bf5c269-5a66-4c28-942a-edfa9af5cecd'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=155, verbose_name='Name')),
                ('Cover', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Cover')),
                ('date', models.DateField()),
                ('artists', models.ManyToManyField(related_name='single_artists', to='main.artist', verbose_name='Artists')),
                ('feat', models.ManyToManyField(blank=True, null=True, to='main.artist', verbose_name='Featuring Artists')),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.format', verbose_name='Drop Type')),
            ],
            options={
                'verbose_name': 'Single',
                'verbose_name_plural': 'Singles',
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('ba74e5fa-df93-4882-adb5-878c883b7587'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=155, verbose_name='Name')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Cover')),
                ('date', models.DateField()),
                ('artists', models.ManyToManyField(related_name='album_artists', to='main.artist', verbose_name='Artists')),
                ('feat', models.ManyToManyField(blank=True, null=True, to='main.artist', verbose_name='Featuring Artists')),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.format', verbose_name='Drop Type')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
            },
        ),
    ]
