# Generated by Django 4.2 on 2023-04-30 18:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='slug_id',
        ),
        migrations.AddField(
            model_name='artist',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b9db0590-add0-45dc-93d5-14cbc3172fc7'), editable=False, primary_key=True, serialize=False),
        ),
    ]
