# Generated by Django 4.2 on 2023-05-03 23:29

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_album_uuid_alter_artist_uuid_alter_single_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='single',
            name='Cover',
        ),
        migrations.AddField(
            model_name='single',
            name='file',
            field=models.FileField(default=1, upload_to='audio', validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav'])], verbose_name='Single File'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('433e36b2-f7cc-4ee0-8c48-4754fe4a1c7e'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='artist',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d143177d-93c3-4b28-a334-cb38944fe5fe'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='single',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('5021fc44-a6be-4e28-a7d4-7a72fadbf890'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='single',
            name='cover',
            field=models.ImageField(blank=True, upload_to='img', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg'])], verbose_name='Single Cover'),
        ),
    ]
