# Generated by Django 4.2 on 2023-05-08 23:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_single_cover_single_file_alter_album_uuid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='format',
        ),
        migrations.RemoveField(
            model_name='single',
            name='format',
        ),
        migrations.AlterField(
            model_name='album',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f69a46f7-358a-4d16-8a56-2ff694e5cfaf'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='artist',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d2e63e38-17f6-459e-b389-862d8c1e6cd4'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='single',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('71e6a915-d6c9-4430-bc67-e0997f610b15'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Format',
        ),
    ]
