# Generated by Django 4.2 on 2023-06-02 10:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_album_format_remove_single_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('9874d15a-42e8-4a87-bd10-7ea4a7a10562'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='artist',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('8bc77248-fbc7-494c-a6f9-4c7428b374f0'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='single',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('c51a2fad-5751-484d-b79e-bbd03fd599f0'), editable=False, primary_key=True, serialize=False),
        ),
    ]
