# Generated by Django 4.2 on 2023-06-02 10:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_album_uuid_alter_artist_uuid_alter_single_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d11e5b6b-ca59-48bc-b9db-c38bb10524da'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='artist',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('cb263f0c-0130-11ee-a1a3-106fd93325a6'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='single',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f0f15e9e-0108-48ad-8886-34207ce957e0'), editable=False, primary_key=True, serialize=False),
        ),
    ]
